

HOST = "localhost"
BASE_URL_GEORESOLVE = f"http://{HOST}:8000"
BASE_URL_GEOREQUEST = f"http://{HOST}:8001"
BASE_URL_SERVER = f"http://{HOST}:8004"
BASE_URL_STATUS = f"http://{HOST}:8005"
BASE_URL_POPULARITY = f"http://{HOST}:8006"
BASE_URL_COUNTRY = f"http://{HOST}:8007"
BASE_URL_TESTS = f"http://{HOST}:8008"
BASE_URL_LOGIN = f"http://{HOST}:8009"
